### ISSUE TITLE
Task 11: task and solution identical

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/express-workshop#12]
https://github.com/foundersandcoders/express-workshop/blob/master/11-handle-errors/src/app.js

**Comment by jwld** [comment]
@mantagen just going through this workshop with someone here, and it looks like you removed the solution from the [solution file](https://github.com/foundersandcoders/express-workshop/blob/master/solution/11-handle-errors/src/app.js), but left it in the [main workshop file](https://github.com/foundersandcoders/express-workshop/blob/master/11-handle-errors/src/app.js)

**Comment by mantagen** [comment]
@JWLD what am I _like_!
Any chance you could submit a PR for this? My hands are pretty tied at the mo!
 .... hmm. who's doing express week

**Comment by mantagen** [comment]
I falls under my responsibility to do it, seeing as I did the first one, so I will certainly try to find time

But in the mean time if anyone else does have the time...

**Comment by jwld** [comment]
Done @mantagen

**Comment by SleepySheepy172** [comment]
@mantagen @JWLD so this is done? can the issue be closed now?

**Comment by jwld** [comment]
I believe so @SleepySheepy172 !
