### ISSUE TITLE
Relative resource paths in error page html should be absolute

### ISSUE THREAD

**Issue by BartBucknill** [foundersandcoders/express-workshop#17]
When rendering error pages on urls such as 'localhost:3000/aaaa/aaaa', the resources requested by the page (css, image, js) do not load, because the path given in the html is relative not absolute; they should be absolute so that express.static can correctly find the resource.
For example, the css is requested as:
* currently relative: 'css/styles.css'
* it should be absolute: '/css/styles.css'

EDIT:
Additionally, in other html files the other resources should also be requested at absolute paths. Currently going to 'localhost:3000/fruit' works fine, but 'localhost:3000/fruit/' will prepend 'fruit' to the request for other resources at relative paths such as 'css/styles.css', causing the stylesheet to fail to load. It fails to load because express.static is looking in the public directory for '/fruit/css/styles.css', which does not exist. *Resource paths in all html files for this workshop should be absolute.*

**Comment by astroash** [comment]
@BartBucknill @eliascodes can this issue be closed?
