### ISSUE TITLE
Confusing text in Library vs framework section

### ISSUE THREAD

**Issue by finnhodgkin** [foundersandcoders/express-workshop#2]
It's a really nice clear intro to Express until this sentence, which I think contains too many beginner un-friendly buzzwords:

> In order to use it you need to insert your behaviour into various places in the framework __either by subclassing or by plugging in your own classes__.

I'd just remove the bold section, it's confusing and not even necessarily true for all frameworks.

(HI! Can't wait to see you and Akin next week!)

**Comment by PiotrBerebecki** [comment]
Thanks @finnhodgkin, I've removed it.
See you soon 😄

**Comment by BartBucknill** [comment]
@finnhodgkin can we close this?

**Comment by finnhodgkin** [comment]
:+1:
