### ISSUE TITLE
"solutions" to "tasks"?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/express-workshop#3]
Especially given that this is a code along, it would be good to have the final, "correct" code written somewhere

**Comment by PiotrBerebecki** [comment]
Hi @jsms90 😄 I've just double-checked and all solutions have been added to the `solution` branch.

**Comment by BartBucknill** [comment]
@jsms90 Can we close this issue out?

**Comment by SleepySheepy172** [comment]
@jsms90 we (fac14) are now going through all the issues in preparation for mentoring fac15 so if this issue has been addressed can it be closed now?

**Comment by BartBucknill** [comment]
@SleepySheepy172 I think this is closed; if you agree I would just go ahead and close it.
